app_name: overseas-entities-api
group: api

weight: 100
routes:
 1: ^/transactions/(.*)/overseas-entity/*
 2: ^/private/transactions/(.*)/overseas-entity/(.*)/filings
 3: ^/overseas-entity/healthcheck
 4: ^/private/transactions/(.*)/overseas-entity/(.*)/*
 5: ^/private/transactions/(.*)/overseas-entity/(.*)/trusts/(.*)/individual-trustees
 6: ^/private/transactions/(.*)/overseas-entity/(.*)/trusts/(.*)/corporate-trustees
 7: ^/private/transactions/(.*)/overseas-entity/(.*)/trusts/details
 8: ^/private/transactions/(.*)/overseas-entity/(.*)/trusts/beneficial-owners/links

