package uk.gov.companieshouse.overseasentitiesapi.validation.utils;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class CountryLists {

        private static final List<String> overseasCountries;
        private static final List<String> ukCountries;
        private static final List<String> allCountries;

        private CountryLists() {}

        static {
            List<String> oeTempList = new ArrayList<>();
            oeTempList.add("Afghanistan");
            oeTempList.add("Aland Islands");
            oeTempList.add("Albania");
            oeTempList.add("Alderney");
            oeTempList.add("Algeria");
            oeTempList.add("American Samoa");
            oeTempList.add("Andorra");
            oeTempList.add("Angola");
            oeTempList.add("Anguilla");
            oeTempList.add("Antarctica");
            oeTempList.add("Antigua and Barbuda");
            oeTempList.add("Argentina");
            oeTempList.add("Armenia");
            oeTempList.add("Aruba");
            oeTempList.add("Australia");
            oeTempList.add("Austria");
            oeTempList.add("Azerbaijan");
            oeTempList.add("Bahamas");
            oeTempList.add("Bahrain");
            oeTempList.add("Bangladesh");
            oeTempList.add("Barbados");
            oeTempList.add("Belarus");
            oeTempList.add("Belgium");
            oeTempList.add("Belize");
            oeTempList.add("Benin");
            oeTempList.add("Bermuda");
            oeTempList.add("Bhutan");
            oeTempList.add("Bolivia");
            oeTempList.add("Bonaire, Sint Eustatius and Saba");
            oeTempList.add("Bosnia and Herzegovina");
            oeTempList.add("Botswana");
            oeTempList.add("Bouvet Island");
            oeTempList.add("Brazil");
            oeTempList.add("British Indian Ocean Territory");
            oeTempList.add("Brunei Darussalam");
            oeTempList.add("Bulgaria");
            oeTempList.add("Burkina Faso");
            oeTempList.add("Burundi");
            oeTempList.add("Cambodia");
            oeTempList.add("Cameroon");
            oeTempList.add("Canada");
            oeTempList.add("Cape Verde");
            oeTempList.add("Cayman Islands");
            oeTempList.add("Central African Republic");
            oeTempList.add("Chad");
            oeTempList.add("Chile");
            oeTempList.add("China");
            oeTempList.add("Christmas Island");
            oeTempList.add("Cocos (Keeling) Islands");
            oeTempList.add("Colombia");
            oeTempList.add("Comoros");
            oeTempList.add("Congo");
            oeTempList.add("Congo, the Democratic Republic of the");
            oeTempList.add("Cook Islands");
            oeTempList.add("Costa Rica");
            oeTempList.add("Croatia");
            oeTempList.add("Cuba");
            oeTempList.add("Curacao");
            oeTempList.add("Cyprus");
            oeTempList.add("Czech Republic");
            oeTempList.add("Denmark");
            oeTempList.add("Djibouti");
            oeTempList.add("Dominica");
            oeTempList.add("Dominican Republic");
            oeTempList.add("East Timor");
            oeTempList.add("Ecuador");
            oeTempList.add("Egypt");
            oeTempList.add("El Salvador");
            oeTempList.add("Equatorial Guinea");
            oeTempList.add("Eritrea");
            oeTempList.add("Estonia");
            oeTempList.add("Eswatini");
            oeTempList.add("Ethiopia");
            oeTempList.add("Falkland Islands");
            oeTempList.add("Faroe Islands");
            oeTempList.add("Fiji");
            oeTempList.add("Finland");
            oeTempList.add("France");
            oeTempList.add("French Guiana");
            oeTempList.add("French Polynesia");
            oeTempList.add("French Southern Territories");
            oeTempList.add("Gabon");
            oeTempList.add("Gambia");
            oeTempList.add("Georgia");
            oeTempList.add("Germany");
            oeTempList.add("Ghana");
            oeTempList.add("Gibraltar");
            oeTempList.add("Greece");
            oeTempList.add("Greenland");
            oeTempList.add("Grenada");
            oeTempList.add("Guadeloupe");
            oeTempList.add("Guam");
            oeTempList.add("Guatemala");
            oeTempList.add("Guernsey");
            oeTempList.add("Guinea");
            oeTempList.add("Guinea-Bissau");
            oeTempList.add("Guyana");
            oeTempList.add("Haiti");
            oeTempList.add("Heard Island and McDonald Islands");
            oeTempList.add("Herm");
            oeTempList.add("Honduras");
            oeTempList.add("Hong Kong");
            oeTempList.add("Hungary");
            oeTempList.add("Iceland");
            oeTempList.add("India");
            oeTempList.add("Indonesia");
            oeTempList.add("Iran");
            oeTempList.add("Iraq");
            oeTempList.add("Ireland");
            oeTempList.add("Isle of Man");
            oeTempList.add("Israel");
            oeTempList.add("Italy");
            oeTempList.add("Ivory Coast");
            oeTempList.add("Jamaica");
            oeTempList.add("Japan");
            oeTempList.add("Jersey");
            oeTempList.add("Jordan");
            oeTempList.add("Kazakhstan");
            oeTempList.add("Kenya");
            oeTempList.add("Kiribati");
            oeTempList.add("Kosovo");
            oeTempList.add("Kuwait");
            oeTempList.add("Kyrgyzstan");
            oeTempList.add("Laos");
            oeTempList.add("Latvia");
            oeTempList.add("Lebanon");
            oeTempList.add("Lesotho");
            oeTempList.add("Liberia");
            oeTempList.add("Libya");
            oeTempList.add("Liechtenstein");
            oeTempList.add("Lithuania");
            oeTempList.add("Luxembourg");
            oeTempList.add("Macao");
            oeTempList.add("Macedonia");
            oeTempList.add("Madagascar");
            oeTempList.add("Malawi");
            oeTempList.add("Malaysia");
            oeTempList.add("Maldives");
            oeTempList.add("Mali");
            oeTempList.add("Malta");
            oeTempList.add("Marshall Islands");
            oeTempList.add("Martinique");
            oeTempList.add("Mauritania");
            oeTempList.add("Mauritius");
            oeTempList.add("Mayotte");
            oeTempList.add("Mexico");
            oeTempList.add("Micronesia");
            oeTempList.add("Moldova");
            oeTempList.add("Monaco");
            oeTempList.add("Mongolia");
            oeTempList.add("Montenegro");
            oeTempList.add("Montserrat");
            oeTempList.add("Morocco");
            oeTempList.add("Mozambique");
            oeTempList.add("Myanmar");
            oeTempList.add("Namibia");
            oeTempList.add("Nauru");
            oeTempList.add("Nepal");
            oeTempList.add("Netherlands");
            oeTempList.add("New Caledonia");
            oeTempList.add("New Zealand");
            oeTempList.add("Nicaragua");
            oeTempList.add("Niger");
            oeTempList.add("Nigeria");
            oeTempList.add("Niue");
            oeTempList.add("Norfolk Island");
            oeTempList.add("North Korea");
            oeTempList.add("Northern Mariana Islands");
            oeTempList.add("Norway");
            oeTempList.add("Oman");
            oeTempList.add("Pakistan");
            oeTempList.add("Palau");
            oeTempList.add("Palestine, State of");
            oeTempList.add("Panama");
            oeTempList.add("Papua New Guinea");
            oeTempList.add("Paraguay");
            oeTempList.add("Peru");
            oeTempList.add("Philippines");
            oeTempList.add("Pitcairn");
            oeTempList.add("Poland");
            oeTempList.add("Portugal");
            oeTempList.add("Puerto Rico");
            oeTempList.add("Qatar");
            oeTempList.add("Reunion");
            oeTempList.add("Romania");
            oeTempList.add("Russia");
            oeTempList.add("Rwanda");
            oeTempList.add("Saint Barthelemy");
            oeTempList.add("Saint Helena, Ascension and Tristan da Cunha");
            oeTempList.add("Saint Kitts and Nevis");
            oeTempList.add("Saint Lucia");
            oeTempList.add("Saint Martin (French part)");
            oeTempList.add("Saint Pierre and Miquelon");
            oeTempList.add("Saint Vincent and the Grenadines");
            oeTempList.add("Samoa");
            oeTempList.add("San Marino");
            oeTempList.add("Sao Tome and Principe");
            oeTempList.add("Sark");
            oeTempList.add("Saudi Arabia");
            oeTempList.add("Senegal");
            oeTempList.add("Serbia");
            oeTempList.add("Seychelles");
            oeTempList.add("Sierra Leone");
            oeTempList.add("Singapore");
            oeTempList.add("Sint Maarten (Dutch part)");
            oeTempList.add("Slovakia");
            oeTempList.add("Slovenia");
            oeTempList.add("Solomon Islands");
            oeTempList.add("Somalia");
            oeTempList.add("South Africa");
            oeTempList.add("South Georgia and the South Sandwich Islands");
            oeTempList.add("South Korea");
            oeTempList.add("South Sudan");
            oeTempList.add("Spain");
            oeTempList.add("Sri Lanka");
            oeTempList.add("Sudan");
            oeTempList.add("Suriname");
            oeTempList.add("Svalbard and Jan Mayen");
            oeTempList.add("Sweden");
            oeTempList.add("Switzerland");
            oeTempList.add("Syria");
            oeTempList.add("Taiwan");
            oeTempList.add("Tajikistan");
            oeTempList.add("Tanzania");
            oeTempList.add("Thailand");
            oeTempList.add("Togo");
            oeTempList.add("Tokelau");
            oeTempList.add("Tonga");
            oeTempList.add("Trinidad and Tobago");
            oeTempList.add("Tunisia");
            oeTempList.add("Turkey");
            oeTempList.add("Turkmenistan");
            oeTempList.add("Turks and Caicos Islands");
            oeTempList.add("Tuvalu");
            oeTempList.add("Uganda");
            oeTempList.add("Ukraine");
            oeTempList.add("United Arab Emirates");
            oeTempList.add("United States");
            oeTempList.add("United States Minor Outlying Islands");
            oeTempList.add("Uruguay");
            oeTempList.add("Uzbekistan");
            oeTempList.add("Vanuatu");
            oeTempList.add("Vatican City");
            oeTempList.add("Venezuela");
            oeTempList.add("Vietnam");
            oeTempList.add("Virgin Islands, British");
            oeTempList.add("Virgin Islands, U.S.");
            oeTempList.add("Wallis and Futuna");
            oeTempList.add("Western Sahara");
            oeTempList.add("Yemen");
            oeTempList.add("Zambia");
            oeTempList.add("Zimbabwe");
            overseasCountries = Collections.unmodifiableList(oeTempList);

            List<String> ukTempList = new ArrayList<>();
            ukTempList.add("United Kingdom");
            ukTempList.add("England");
            ukTempList.add("Northern Ireland");
            ukTempList.add("Scotland");
            ukTempList.add("Wales");
            ukCountries = Collections.unmodifiableList(ukTempList);

            List<String> allCountriesTempList = new ArrayList<>();
            allCountriesTempList.addAll(overseasCountries);
            allCountriesTempList.addAll(ukCountries);
            allCountries = Collections.unmodifiableList(allCountriesTempList);
        }


        public static List<String> getOverseasCountries() {
           return overseasCountries;
        }

        public static List<String> getUkCountries() {
           return ukCountries;
        }

        public static List<String> getAllCountries() {
            return allCountries;
        }
}
