package uk.gov.companieshouse.overseasentitiesapi.utils;

public class MockData {

    public static final String jsonBeneficialOwnerString = "["
            + "{"
            + "\"id\":\"9001808903\","
            + "\"date_became_registrable\":\"2023-04-13 00:00:00.0\","
            + "\"is_service_address_same_as_usual_address\":\"N\","
            + "\"date_of_birth\":\"2023-04-13 00:00:00.0\","
            + "\"usual_residential_address\":{"
            + "\"address_line_1\":\"491 SOUTH GREEN OLD BOULEVARD\","
            + "\"address_line_2\":\"SIT NON PRAESENTIUM\","
            + "\"care_of\":null,"
            + "\"country\":\"ITALY\","
            + "\"locality\":\"EXPEDITA IN OFFICIIS\","
            + "\"po_box\":null,"
            + "\"postal_code\":\"29765\","
            + "\"premises\":\"DUSTIN MONTOYA\","
            + "\"region\":\"ULLAM AUTEM IMPEDIT\""
            + "},"
            + "\"principal_address\":{"
            + "\"address_line_1\":null,"
            + "\"address_line_2\":null,"
            + "\"care_of\":null,"
            + "\"country\":null,"
            + "\"locality\":null,"
            + "\"po_box\":null,"
            + "\"postal_code\":null,"
            + "\"premises\":null,"
            + "\"region\":null"
            + "}"
            + "},"
            + "{"
            + "\"id\":\"9001808904\","
            + "\"date_became_registrable\":\"2023-04-13 00:00:00.0\","
            + "\"is_service_address_same_as_usual_address\":\"N\","
            + "\"date_of_birth\":null,"
            + "\"usual_residential_address\":{"
            + "\"address_line_1\":null,"
            + "\"address_line_2\":null,"
            + "\"care_of\":null,"
            + "\"country\":null,"
            + "\"locality\":null,"
            + "\"po_box\":null,"
            + "\"postal_code\":null,"
            + "\"premises\":null,"
            + "\"region\":null"
            + "},"
            + "\"principal_address\":{"
            + "\"address_line_1\":\"204 NOBEL DRIVE\","
            + "\"address_line_2\":\"ASPERIORES VOLUPTATE\","
            + "\"care_of\":null,"
            + "\"country\":\"MACEDONIA\","
            + "\"locality\":\"VELIT UT FACILIS VE\","
            + "\"po_box\":null,"
            + "\"postal_code\":\"41608\","
            + "\"premises\":\"MEGAN WILDER\","
            + "\"region\":\"ID AUT OFFICIA CUPI\""
            + "}"
            + "},"
            + "{"
            + "\"id\":\"9001808905\","
            + "\"date_became_registrable\":\"2023-04-13 00:00:00.0\","
            + "\"is_service_address_same_as_usual_address\":\"N\","
            + "\"date_of_birth\":null,"
            + "\"usual_residential_address\":{"
            + "\"address_line_1\":null,"
            + "\"address_line_2\":null,"
            + "\"care_of\":null,"
            + "\"country\":null,"
            + "\"locality\":null,"
            + "\"po_box\":null,"
            + "\"postal_code\":null,"
            + "\"premises\":null,"
            + "\"region\":null"
            + "},"
            + "\"principal_address\":{"
            + "\"address_line_1\":\"55 GREEN COWLEY PARKWAY\","
            + "\"address_line_2\":\"DISTINCTIO FACILIS\","
            + "\"care_of\":null,"
            + "\"country\":\"MAURITIUS\","
            + "\"locality\":\"CULPA EOS ENIM QUI\","
            + "\"po_box\":null,"
            + "\"postal_code\":\"90079\","
            + "\"premises\":\"CORA BENTON\","
            + "\"region\":\"IN VELIT ET EIUS MIN\""
            + "}"
            + "}"
            + "]";
}
